version: "3"
services:
  server:
    init: true
    build: ./server
    volumes:
      - ./server:/app:z
    ports:
      - "5000:5000"
    command: sh -c "chmod +x /app/run.sh && ./run.sh"
  client:
    build: ./client
    # Attach current folders as volumes
    volumes:
      - ./client:/app:z
    environment:
      - SERVER_HOST=server
      - PYTHONUNBUFFERED=1
    command: sh -c "python client.py"
